import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

// Premium high-res images (q=95, large crops)
const U = "https://images.unsplash.com";
const sq = (id: string) =>
  `${U}/${id}?auto=format&fit=crop&w=1200&h=1200&q=95`;
const cat = (id: string) =>
  `${U}/${id}?auto=format&fit=crop&w=800&h=800&q=95`;

const img = {
  serum: sq("photo-1631730486572-226d1f595b68"),
  serum2: sq("photo-1611930022073-b7a4ba5fcccd"),
  serum3: sq("photo-1608248543803-ba4f8c70ae0b"),
  facewash: sq("photo-1556228578-0d85b1a4d571"),
  cleanser: sq("photo-1556228720-195a672e8a03"),
  sunscreen: sq("photo-1556229010-6c3f2c9ca5f8"),
  shampoo: sq("photo-1527799820374-dcf8d9d4a388"),
  lotion: sq("photo-1556228453-efd6c1ff04f6"),
  cream: sq("photo-1598440947619-2c35fc9aa908"),
  cream2: sq("photo-1608571423902-eed4a5ad8108"),
  vitamins: sq("photo-1607619056574-7b8d3ee536b2"),
  vitamins2: sq("photo-1584308666744-24d5c474f2ae"),
  medicine: sq("photo-1587854692152-cbe660dbde88"),
  pills: sq("photo-1471864190281-a93a3070b6de"),
  baby: sq("photo-1515488042361-ee00e0ddd4e4"),
  herbal: sq("photo-1512290923902-8a9f81dc236c"),
  herbs: sq("photo-1515377905703-c4788e51af15"),
  device: sq("photo-1631815588090-d4bfec5b1ccb"),
  oil: sq("photo-1600857062241-98e5dba7f214"),
  soap: sq("photo-1600857544200-b2f666a9a2ec"),
  mask: sq("photo-1596755389378-c31d21fd1273"),
  protein: sq("photo-1593095948071-474c5cc2989d"),
  pet: sq("photo-1450778869180-41d0601e046e"),
  home: sq("photo-1584622650111-993a426fbf0a"),
  beauty: sq("photo-1596462502278-27bfdc403348"),
  makeup: sq("photo-1522335789203-aabd1fc54bc9"),
  spa: sq("photo-1570172619644-dfd03ed5d881"),
  food: sq("photo-1490645935967-10de6ba17061"),
  wellness: sq("photo-1544367567-0f2fcb009e0b"),
  lab: sq("photo-1579154204601-01588f351e67"),
  banner1: "/uploads/brand/heroes/pharmacy.jpg",
  banner2: "/uploads/brand/heroes/beauty.jpg",
  banner3: "/uploads/brand/heroes/doctor.jpg",
  banner4: "/uploads/brand/heroes/lab.jpg",
  catMedicine: cat("photo-1587854692152-cbe660dbde88"),
  catBeauty: cat("photo-1596462502278-27bfdc403348"),
  catLab: cat("photo-1579154204601-01588f351e67"),
  catFood: cat("photo-1490645935967-10de6ba17061"),
  catBaby: cat("photo-1515488042361-ee00e0ddd4e4"),
  catHome: cat("photo-1584622650111-993a426fbf0a"),
  catPet: cat("photo-1450778869180-41d0601e046e"),
  catHealth: cat("photo-1571019614242-c5c5dee9f50b"),
  catHerbal: cat("photo-1512290923902-8a9f81dc236c"),
  catHair: cat("photo-1527799820374-dcf8d9d4a388"),
  catSkin: cat("photo-1570172619644-dfd03ed5d881"),
  catSupp: cat("photo-1607619056574-7b8d3ee536b2"),
  catDevice: cat("photo-1631815588090-d4bfec5b1ccb"),
};

async function main() {
  await prisma.prescriptionItem.deleteMany();
  await prisma.prescription.deleteMany();
  await prisma.consultation.deleteMany();
  await prisma.doctorSettlement.deleteMany();
  await prisma.doctorSchedule.deleteMany();
  await prisma.doctor.deleteMany();
  await prisma.labBooking.deleteMany();
  await prisma.labPackageItem.deleteMany();
  await prisma.labPackage.deleteMany();
  await prisma.labTest.deleteMany();
  await prisma.productNotify.deleteMany();
  await prisma.productReview.deleteMany();
  await prisma.stockMovement.deleteMany();
  await prisma.productVariant.deleteMany();
  await prisma.refundRequest.deleteMany();
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.coupon.deleteMany();
  await prisma.supportTicket.deleteMany();
  await prisma.product.deleteMany();
  await prisma.banner.deleteMany();
  await prisma.brand.deleteMany();
  await prisma.category.deleteMany();
  await prisma.vendor.deleteMany();
  await prisma.rider.deleteMany();
  await prisma.adminUser.deleteMany();

  const categories = await Promise.all(
    [
      { name: "Medicine", slug: "medicine", image: img.catMedicine, color: "#E8F0EF", sortOrder: 1 },
      { name: "Beauty", slug: "beauty", image: img.catBeauty, color: "#F7F0F2", sortOrder: 2 },
      { name: "Home Lab", slug: "home-lab", image: img.catLab, color: "#EBF2F5", sortOrder: 3 },
      { name: "Food & Nutrition", slug: "food-nutrition", image: img.catFood, color: "#F5F0E8", sortOrder: 4 },
      { name: "Baby & Mom Care", slug: "baby-mom", image: img.catBaby, color: "#F3EEF5", sortOrder: 5 },
      { name: "Homecare", slug: "homecare", image: img.catHome, color: "#EAF3F2", sortOrder: 6 },
      { name: "Pet Care", slug: "pet-care", image: img.catPet, color: "#F5F2E9", sortOrder: 7 },
      { name: "Healthcare", slug: "healthcare", image: img.catHealth, color: "#EEF0F5", sortOrder: 8 },
      { name: "Herbal", slug: "herbal", image: img.catHerbal, color: "#EBF2EC", sortOrder: 9 },
      { name: "Haircare", slug: "haircare", image: img.catHair, color: "#F2EEEA", sortOrder: 10 },
      { name: "Skincare", slug: "skincare", image: img.catSkin, color: "#F7F0F0", sortOrder: 11 },
      { name: "Supplement", slug: "supplement", image: img.catSupp, color: "#EBF3F1", sortOrder: 12 },
      { name: "Medical Devices", slug: "medical-devices", image: img.catDevice, color: "#EEEFF1", sortOrder: 13 },
      { name: "Sexual Wellness", slug: "sexual-wellness", image: img.wellness, color: "#F3EEF5", sortOrder: 14 },
      { name: "Feminine Care", slug: "feminine-care", image: img.beauty, color: "#F7F0F2", sortOrder: 15 },
      { name: "Homeopathy", slug: "homeopathy", image: img.herbs, color: "#EBF2EC", sortOrder: 16 },
      { name: "Veterinary", slug: "veterinary", image: img.pet, color: "#F5F2E9", sortOrder: 17 },
      { name: "Dermatological", slug: "dermatological", image: img.spa, color: "#F7F0F0", sortOrder: 18 },
    ].map((c) => prisma.category.create({ data: c }))
  );

  const catMap = Object.fromEntries(categories.map((c) => [c.slug, c.id]));

  const brands = await Promise.all(
    [
      { name: "Skin'O", slug: "skino" },
      { name: "Innsaei", slug: "innsaei" },
      { name: "Himalaya", slug: "himalaya" },
      { name: "The Dermalix", slug: "dermalix" },
      { name: "GFORS", slug: "gfors" },
      { name: "Seravix", slug: "seravix" },
      { name: "Ahona Care", slug: "ahona-care" },
      { name: "NaturaPlus", slug: "naturaplus" },
    ].map((b) => prisma.brand.create({ data: b }))
  );

  const brand = Object.fromEntries(brands.map((b) => [b.slug, b.id]));

  type P = {
    name: string;
    slug: string;
    description: string;
    shortDesc?: string;
    image: string;
    gallery?: string[];
    price: number;
    comparePrice?: number;
    rating?: number;
    reviewCount?: number;
    categoryId: string;
    brandId?: string;
    isFeatured?: boolean;
    isFlashSale?: boolean;
    tags?: string[];
    section?: string;
    unit?: string;
  };

  const products: P[] = [
    {
      name: "Skin'O Lavender Soothing Shower Gel 220ml (Buy 1 Get 1)",
      slug: "skino-lavender-shower-gel-bogo",
      description:
        "Premium lavender-infused shower gel that soothes and hydrates. Buy 1 Get 1 Free. Dermatologically tested.",
      shortDesc: "Buy 1 Get 1 Free · Lavender calm",
      image: img.lotion,
      gallery: [img.lotion, img.spa, img.cream],
      price: 250,
      comparePrice: 500,
      rating: 4.8,
      reviewCount: 388,
      categoryId: catMap.skincare,
      brandId: brand.skino,
      isFeatured: true,
      tags: ["bogo"],
      section: "skino-deals",
    },
    {
      name: "Skin'O Keratin Smooth Repair Shampoo 220ml (Buy 1 Get 1)",
      slug: "skino-keratin-shampoo-bogo",
      description: "Keratin-enriched shampoo for silky smooth hair. Buy 1 Get 1 Free.",
      image: img.shampoo,
      gallery: [img.shampoo, img.oil, img.beauty],
      price: 340,
      comparePrice: 350,
      rating: 4.7,
      reviewCount: 314,
      categoryId: catMap.haircare,
      brandId: brand.skino,
      section: "skino-deals",
    },
    {
      name: "Skin'O Vitamin E Brightening Facewash 110ml (Buy 1 Get 1)",
      slug: "skino-vitamin-e-facewash-bogo",
      description: "Gentle brightening facewash with Vitamin E. Buy 1 Get 1 Free.",
      image: img.facewash,
      gallery: [img.facewash, img.cleanser, img.spa],
      price: 200,
      comparePrice: 220,
      rating: 4.6,
      reviewCount: 171,
      categoryId: catMap.skincare,
      brandId: brand.skino,
      section: "skino-deals",
    },
    {
      name: "Innsaei Salicylic Acid Acne Cleansing Foam 150ml",
      slug: "innsaei-salicylic-acne-foam",
      description: "Deep-cleansing foam with salicylic acid to fight acne and control oil.",
      image: img.cleanser,
      gallery: [img.cleanser, img.facewash, img.serum],
      price: 288,
      comparePrice: 360,
      rating: 4.7,
      reviewCount: 257,
      categoryId: catMap.skincare,
      brandId: brand.innsaei,
      isFeatured: true,
      section: "skino-deals",
    },
    {
      name: "Skin'O Acne + Spot Treatment Serum 30ml",
      slug: "skino-acne-spot-serum",
      description: "Targeted acne and spot treatment serum for clearer skin.",
      image: img.serum,
      gallery: [img.serum, img.serum2, img.serum3],
      price: 365,
      comparePrice: 490,
      rating: 4.5,
      reviewCount: 58,
      categoryId: catMap.skincare,
      brandId: brand.skino,
      section: "skino-deals",
    },
    {
      name: "Innsaei Hyaluronic Sunscreen SPF50 50ml",
      slug: "innsaei-hyaluronic-sunscreen",
      description: "Lightweight hyaluronic sunscreen SPF 50 PA+++.",
      image: img.sunscreen,
      gallery: [img.sunscreen, img.spa, img.lotion],
      price: 552,
      comparePrice: 690,
      rating: 4.8,
      reviewCount: 36,
      categoryId: catMap.skincare,
      brandId: brand.innsaei,
      isFeatured: true,
      isFlashSale: true,
      section: "skino-deals",
    },
    {
      name: "Innsaei Low pH Daily Gel Cleanser 5.5 150ml (B1G1)",
      slug: "innsaei-low-ph-cleanser-bogo",
      description: "pH-balanced gel cleanser. Buy 1 Get 1 Free.",
      image: img.facewash,
      gallery: [img.facewash, img.cleanser],
      price: 345,
      comparePrice: 360,
      rating: 4.9,
      reviewCount: 600,
      categoryId: catMap.skincare,
      brandId: brand.innsaei,
      section: "skino-deals",
    },
    {
      name: "Skin'O Daily Gel Moisturizer Niacinamide 70ml",
      slug: "skino-gel-moisturizer-niacinamide",
      description: "Lightweight gel moisturizer with niacinamide and green tea.",
      image: img.cream,
      gallery: [img.cream, img.cream2, img.serum],
      price: 285,
      comparePrice: 390,
      rating: 4.6,
      reviewCount: 221,
      categoryId: catMap.skincare,
      brandId: brand.skino,
      section: "skino-deals",
    },
    {
      name: "The Dermalix 10% Vitamin C Glow Serum 30ml",
      slug: "dermalix-vitamin-c-serum",
      description: "Potent 10% Vitamin C serum for radiant, even-toned skin.",
      image: img.serum2,
      gallery: [img.serum2, img.serum, img.beauty],
      price: 645,
      comparePrice: 890,
      rating: 4.7,
      reviewCount: 42,
      categoryId: catMap.skincare,
      brandId: brand.dermalix,
      isFeatured: true,
      section: "all-in-one",
    },
    {
      name: "The Dermalix Niacinamide 4% + Alpha Arbutin Serum 30ml",
      slug: "dermalix-niacinamide-arbutin-serum",
      description: "Brightening serum with niacinamide and alpha arbutin.",
      image: img.serum3,
      gallery: [img.serum3, img.serum2],
      price: 585,
      comparePrice: 890,
      rating: 4.6,
      reviewCount: 28,
      categoryId: catMap.skincare,
      brandId: brand.dermalix,
      section: "all-in-one",
    },
    {
      name: "Seravix Low pH Cleanser 240ml",
      slug: "seravix-low-ph-cleanser",
      description: "Gentle low pH cleanser for all skin types.",
      image: img.cleanser,
      price: 399,
      comparePrice: 550,
      rating: 4.5,
      reviewCount: 15,
      categoryId: catMap.skincare,
      brandId: brand.seravix,
      section: "all-in-one",
    },
    {
      name: "The Dermalix Shea Butter Shower Gel 250ml (B1G1)",
      slug: "dermalix-shea-shower-bogo",
      description: "Luxurious shea butter shower gel. Buy 1 Get 1 Free.",
      image: img.lotion,
      gallery: [img.lotion, img.soap],
      price: 350,
      comparePrice: 700,
      rating: 4.8,
      reviewCount: 12,
      categoryId: catMap.beauty,
      brandId: brand.dermalix,
      isFlashSale: true,
      section: "all-in-one",
    },
    {
      name: "Seravix Moisturizing Cream Ceramide & Retinol 75ml",
      slug: "seravix-ceramide-retinol-cream",
      description: "Rich cream with ceramide and retinol for dry skin.",
      image: img.cream2,
      gallery: [img.cream2, img.cream],
      price: 490,
      comparePrice: 650,
      rating: 4.7,
      reviewCount: 19,
      categoryId: catMap.skincare,
      brandId: brand.seravix,
      section: "all-in-one",
    },
    {
      name: "The Dermalix Premium Cotton Pads 80pcs",
      slug: "dermalix-cotton-pads",
      description: "Soft, lint-free cotton pads for toner and makeup removal.",
      image: img.mask,
      price: 170,
      comparePrice: 250,
      rating: 4.4,
      reviewCount: 8,
      categoryId: catMap.beauty,
      brandId: brand.dermalix,
      section: "all-in-one",
    },
    {
      name: "Himalaya Brightening Vitamin C Orange Face Serum 30ml",
      slug: "himalaya-vitamin-c-serum",
      description: "Natural Vitamin C orange face serum from Himalaya.",
      image: img.serum,
      gallery: [img.serum, img.herbal],
      price: 350,
      comparePrice: 700,
      rating: 4.6,
      reviewCount: 16,
      categoryId: catMap.skincare,
      brandId: brand.himalaya,
      isFeatured: true,
      isFlashSale: true,
      section: "himalaya",
    },
    {
      name: "Himalaya Purifying Neem Face Wash 300ml",
      slug: "himalaya-neem-face-wash",
      description: "Classic purifying neem face wash for clear skin.",
      image: img.herbal,
      gallery: [img.herbal, img.facewash, img.herbs],
      price: 250,
      comparePrice: 500,
      rating: 4.7,
      reviewCount: 33,
      categoryId: catMap.skincare,
      brandId: brand.himalaya,
      section: "himalaya",
    },
    {
      name: "Himalaya Dark Spot Clearing Turmeric Serum 30ml",
      slug: "himalaya-turmeric-serum",
      description: "Turmeric serum that clears dark spots naturally.",
      image: img.serum2,
      price: 350,
      comparePrice: 700,
      rating: 4.5,
      reviewCount: 14,
      categoryId: catMap.skincare,
      brandId: brand.himalaya,
      section: "himalaya",
    },
    {
      name: "Himalaya Anti Hair Fall Bhringaraja Shampoo 170ml",
      slug: "himalaya-anti-hairfall-shampoo",
      description: "Bhringaraja shampoo to reduce hair fall.",
      image: img.shampoo,
      price: 119,
      comparePrice: 270,
      rating: 4.4,
      reviewCount: 22,
      categoryId: catMap.haircare,
      brandId: brand.himalaya,
      isFlashSale: true,
      section: "himalaya",
    },
    {
      name: "Himalaya Baby Powder 100g",
      slug: "himalaya-baby-powder",
      description: "Gentle baby powder with natural ingredients.",
      image: img.baby,
      gallery: [img.baby, img.wellness],
      price: 99,
      comparePrice: 140,
      rating: 4.8,
      reviewCount: 16,
      categoryId: catMap["baby-mom"],
      brandId: brand.himalaya,
      section: "himalaya",
    },
    {
      name: "Himalaya Moisturizing Aloe Vera Face Wash 100ml",
      slug: "himalaya-aloe-face-wash",
      description: "Refreshing aloe vera face wash.",
      image: img.facewash,
      price: 139,
      comparePrice: 225,
      rating: 4.6,
      reviewCount: 50,
      categoryId: catMap.skincare,
      brandId: brand.himalaya,
      section: "himalaya",
    },
    {
      name: "Himalaya Nourishing Skin Cream 50ml",
      slug: "himalaya-nourishing-cream",
      description: "Everyday nourishing cream for soft skin.",
      image: img.cream,
      price: 109,
      comparePrice: 160,
      rating: 4.7,
      reviewCount: 86,
      categoryId: catMap.skincare,
      brandId: brand.himalaya,
      section: "himalaya",
    },
    {
      name: "Himalaya Men Power Bright Licorice Face Wash 100ml",
      slug: "himalaya-men-face-wash",
      description: "Men's face wash with licorice for a bright look.",
      image: img.cleanser,
      price: 149,
      comparePrice: 250,
      rating: 4.5,
      reviewCount: 84,
      categoryId: catMap.skincare,
      brandId: brand.himalaya,
      section: "himalaya",
    },
    {
      name: "GFORS Vitamin Milk Whitening Cream 50ml + Free Cleanser",
      slug: "gfors-vitamin-milk-cream-combo",
      description: "Premium whitening cream with free cleanser.",
      image: img.cream2,
      gallery: [img.cream2, img.beauty, img.spa],
      price: 700,
      comparePrice: 1290,
      rating: 4.6,
      reviewCount: 9,
      categoryId: catMap.skincare,
      brandId: brand.gfors,
      isFeatured: true,
      section: "gfors",
    },
    {
      name: "GFORS Doctor's Choice Pink Tone-up Sunscreen 50ml",
      slug: "gfors-pink-toneup-sunscreen",
      description: "Tone-up sunscreen with pretty pink finish.",
      image: img.sunscreen,
      price: 696,
      comparePrice: 990,
      rating: 4.5,
      reviewCount: 5,
      categoryId: catMap.skincare,
      brandId: brand.gfors,
      section: "gfors",
    },
    {
      name: "GFORS Salicylic Acid Deep Cleansing Foam 150ml",
      slug: "gfors-salicylic-foam",
      description: "Deep cleansing foam for acne-prone skin.",
      image: img.facewash,
      price: 834,
      comparePrice: 1250,
      rating: 4.4,
      reviewCount: 16,
      categoryId: catMap.skincare,
      brandId: brand.gfors,
      section: "gfors",
    },
    {
      name: "GFORS Artemisia Peptide Serum 30ml",
      slug: "gfors-artemisia-peptide-serum",
      description: "Advanced peptide serum with artemisia.",
      image: img.serum,
      gallery: [img.serum, img.serum2, img.serum3],
      price: 1120,
      comparePrice: 1250,
      rating: 4.8,
      reviewCount: 3,
      categoryId: catMap.skincare,
      brandId: brand.gfors,
      section: "gfors",
    },
    {
      name: "GFORS Intense Care All-In-One Snail Cream 50g",
      slug: "gfors-snail-cream",
      description: "Snail mucin all-in-one cream for repair and glow.",
      image: img.cream,
      price: 1050,
      comparePrice: 1250,
      rating: 4.7,
      reviewCount: 7,
      categoryId: catMap.skincare,
      brandId: brand.gfors,
      section: "gfors",
    },
    {
      name: "Ahona Paracetamol 500mg Tablets (20pcs)",
      slug: "ahona-paracetamol-500",
      description: "Trusted pain relief and fever reducer.",
      image: img.pills,
      gallery: [img.pills, img.medicine],
      price: 25,
      comparePrice: 30,
      rating: 4.9,
      reviewCount: 1204,
      categoryId: catMap.medicine,
      brandId: brand["ahona-care"],
      isFeatured: true,
      unit: "box",
    },
    {
      name: "Ahona Vitamin C 1000mg Effervescent (20 tabs)",
      slug: "ahona-vitamin-c-1000",
      description: "High-strength Vitamin C for immunity support.",
      image: img.vitamins,
      gallery: [img.vitamins, img.vitamins2],
      price: 280,
      comparePrice: 350,
      rating: 4.7,
      reviewCount: 456,
      categoryId: catMap.supplement,
      brandId: brand["ahona-care"],
      isFeatured: true,
      isFlashSale: true,
      unit: "tube",
    },
    {
      name: "Digital Blood Pressure Monitor Arm Cuff",
      slug: "digital-bp-monitor",
      description: "Accurate digital BP monitor with large LCD.",
      image: img.device,
      gallery: [img.device, img.lab],
      price: 1890,
      comparePrice: 2490,
      rating: 4.6,
      reviewCount: 89,
      categoryId: catMap["medical-devices"],
      brandId: brand["ahona-care"],
      isFeatured: true,
    },
    {
      name: "NaturaPlus Omega-3 Fish Oil 60 Softgels",
      slug: "naturaplus-omega3",
      description: "Premium fish oil softgels with EPA & DHA.",
      image: img.vitamins2,
      price: 650,
      comparePrice: 850,
      rating: 4.8,
      reviewCount: 134,
      categoryId: catMap.supplement,
      brandId: brand.naturaplus,
    },
    {
      name: "NaturaPlus Multivitamin Daily 30 Tablets",
      slug: "naturaplus-multivitamin",
      description: "Complete daily multivitamin for energy and wellness.",
      image: img.vitamins,
      price: 420,
      comparePrice: 550,
      rating: 4.5,
      reviewCount: 78,
      categoryId: catMap.supplement,
      brandId: brand.naturaplus,
      isFlashSale: true,
    },
    {
      name: "Herbal Digestive Tea Blend 50g",
      slug: "herbal-digestive-tea",
      description: "Natural herbal blend for digestion support.",
      image: img.herbs,
      gallery: [img.herbs, img.herbal],
      price: 180,
      comparePrice: 220,
      rating: 4.4,
      reviewCount: 41,
      categoryId: catMap.herbal,
      brandId: brand.naturaplus,
    },
    {
      name: "Baby Gentle Wash & Shampoo 200ml",
      slug: "baby-gentle-wash",
      description: "Tear-free gentle wash and shampoo for babies.",
      image: img.baby,
      price: 320,
      comparePrice: 400,
      rating: 4.9,
      reviewCount: 210,
      categoryId: catMap["baby-mom"],
      brandId: brand["ahona-care"],
    },
    {
      name: "Whey Protein Chocolate 1kg",
      slug: "whey-protein-chocolate",
      description: "Premium whey protein isolate. 24g protein per serving.",
      image: img.protein,
      gallery: [img.protein, img.food],
      price: 3200,
      comparePrice: 4200,
      rating: 4.7,
      reviewCount: 156,
      categoryId: catMap["food-nutrition"],
      brandId: brand.naturaplus,
      isFeatured: true,
    },
    {
      name: "Pet Multi-Vitamin Soft Chews 60pcs",
      slug: "pet-multivitamin-chews",
      description: "Tasty soft chews for dogs and cats.",
      image: img.pet,
      price: 890,
      comparePrice: 1100,
      rating: 4.6,
      reviewCount: 34,
      categoryId: catMap["pet-care"],
      brandId: brand.naturaplus,
    },
    {
      name: "Antibacterial Hand Sanitizer 500ml",
      slug: "hand-sanitizer-500",
      description: "70% alcohol hand sanitizer. Kills 99.9% germs.",
      image: img.home,
      price: 180,
      comparePrice: 220,
      rating: 4.5,
      reviewCount: 302,
      categoryId: catMap.homecare,
      brandId: brand["ahona-care"],
    },
    {
      name: "Skin'O Tea Tree Toner AHA BHA PHA 100ml",
      slug: "skino-tea-tree-toner",
      description: "Clarifying toner with tea tree and light acids.",
      image: img.serum3,
      price: 246,
      comparePrice: 320,
      rating: 4.5,
      reviewCount: 74,
      categoryId: catMap.skincare,
      brandId: brand.skino,
      section: "skino-deals",
    },
    {
      name: "Organic Olive Oil Hair & Skin 100ml",
      slug: "organic-olive-oil",
      description: "100% organic olive oil for hair and skin.",
      image: img.oil,
      gallery: [img.oil, img.herbal],
      price: 194,
      comparePrice: 220,
      rating: 4.6,
      reviewCount: 79,
      categoryId: catMap.herbal,
      brandId: brand.skino,
    },
    {
      name: "Neem & Turmeric Natural Soap 125g (Buy 3 Get 1)",
      slug: "neem-turmeric-soap-pack",
      description: "Natural neem and turmeric soap bar pack.",
      image: img.soap,
      price: 249,
      comparePrice: 255,
      rating: 4.5,
      reviewCount: 34,
      categoryId: catMap.herbal,
      brandId: brand.himalaya,
      section: "himalaya",
    },
    {
      name: "Clay Stick Mask Purifying Neem 30g",
      slug: "clay-stick-mask-neem",
      description: "Convenient stick clay mask with neem.",
      image: img.mask,
      price: 399,
      comparePrice: 500,
      rating: 4.3,
      reviewCount: 11,
      categoryId: catMap.skincare,
      brandId: brand.himalaya,
      section: "himalaya",
    },
    {
      name: "Glucose Monitoring Kit with Strips",
      slug: "glucose-monitoring-kit",
      description: "Complete blood glucose monitoring system with 25 strips.",
      image: img.device,
      gallery: [img.device, img.lab],
      price: 1450,
      comparePrice: 1890,
      rating: 4.7,
      reviewCount: 67,
      categoryId: catMap["medical-devices"],
      brandId: brand["ahona-care"],
    },
    {
      name: "Immunity Booster Herbal Capsules 60pcs",
      slug: "immunity-herbal-capsules",
      description: "Ayurvedic immunity blend with amla, ashwagandha, and tulsi.",
      image: img.herbal,
      gallery: [img.herbal, img.herbs, img.vitamins],
      price: 480,
      comparePrice: 650,
      rating: 4.5,
      reviewCount: 92,
      categoryId: catMap.herbal,
      brandId: brand.naturaplus,
      isFlashSale: true,
    },
    {
      name: "Luxury Face Serum Discovery Set",
      slug: "luxury-face-serum-discovery",
      description: "Curated premium serum trio for glow and hydration.",
      image: img.beauty,
      gallery: [img.beauty, img.makeup, img.spa],
      price: 1290,
      comparePrice: 1890,
      rating: 4.9,
      reviewCount: 48,
      categoryId: catMap.beauty,
      brandId: brand.dermalix,
      isFeatured: true,
      isFlashSale: true,
    },
    {
      name: "Wellness Daily Ritual Kit",
      slug: "wellness-daily-ritual-kit",
      description: "Vitamins + herbal tea for everyday wellness.",
      image: img.wellness,
      gallery: [img.wellness, img.vitamins, img.herbs],
      price: 890,
      comparePrice: 1200,
      rating: 4.7,
      reviewCount: 61,
      categoryId: catMap.healthcare,
      brandId: brand.naturaplus,
      isFeatured: true,
    },
  ];

  for (const p of products) {
    const gallery = p.gallery ?? [p.image];
    await prisma.product.create({
      data: {
        name: p.name,
        slug: p.slug,
        description: p.description,
        shortDesc: p.shortDesc,
        image: p.image,
        images: gallery,
        price: p.price,
        comparePrice: p.comparePrice,
        rating: p.rating ?? 4.5,
        reviewCount: p.reviewCount ?? 0,
        categoryId: p.categoryId,
        brandId: p.brandId,
        isFeatured: p.isFeatured ?? false,
        isFlashSale: p.isFlashSale ?? false,
        tags: p.tags ?? [],
        section: p.section,
        unit: p.unit ?? "pcs",
        expressDelivery: true,
        stock: 50 + Math.floor(Math.random() * 150),
      },
    });
  }

  await Promise.all(
    [
      {
        title: "Genuine Care, Delivered",
        subtitle: "Licensed pharmacy · Express 12–24h · COD",
        image: img.banner1,
        link: "/category/medicine",
        sortOrder: 1,
      },
      {
        title: "Beauty, Elevated",
        subtitle: "Curated skincare & cosmetics — up to 60% off",
        image: img.banner2,
        link: "/category/beauty",
        sortOrder: 2,
      },
      {
        title: "A Doctor in Minutes",
        subtitle: "Video consults with verified specialists from ৳199",
        image: img.banner3,
        link: "/doctors",
        sortOrder: 3,
      },
      {
        title: "Lab Tests at Home",
        subtitle: "Home sample collection · Digital reports",
        image: img.banner4,
        link: "/lab-test",
        sortOrder: 4,
      },
    ].map((b) => prisma.banner.create({ data: b }))
  );

  // ── Doctors + weekly schedules ─────────────────────────────────
  const doctorPortrait = (id: string) =>
    `${U}/${id}?auto=format&fit=crop&w=800&h=920&q=90`;

  const doctorSeed = [
    {
      slug: "dr-sadia-rahman",
      name: "Dr. Sadia Rahman",
      specialty: "General Physician",
      image: doctorPortrait("photo-1559839734-2b71ea197ec2"),
      experience: 12,
      fee: 299,
      rating: 4.9,
      patients: "5.2k+",
      hospital: "Square Hospital, Dhaka",
      languages: "Bangla, English",
      bio: "Experienced GP specialising in fever, cold, hypertension and primary care. BMDC registered.",
      bmdcNumber: "A-45231",
      isOnline: true,
      days: [0, 1, 2, 3, 4, 5, 6],
      hours: ["09:00", "21:00"],
    },
    {
      slug: "dr-karim-hossain",
      name: "Dr. Karim Hossain",
      specialty: "Cardiologist",
      image: doctorPortrait("photo-1612349317150-e413f6a5b16d"),
      experience: 18,
      fee: 599,
      rating: 4.8,
      patients: "8.1k+",
      hospital: "United Hospital",
      languages: "Bangla, English",
      bio: "Consultant cardiologist — chest pain, hypertension, heart failure and ECG review.",
      bmdcNumber: "A-31890",
      isOnline: true,
      days: [1, 2, 3, 4, 5],
      hours: ["10:00", "18:00"],
    },
    {
      slug: "dr-nusrat-jahan",
      name: "Dr. Nusrat Jahan",
      specialty: "Dermatologist",
      image: doctorPortrait("photo-1594824476967-48c8b964273f"),
      experience: 10,
      fee: 499,
      rating: 4.9,
      patients: "4.6k+",
      hospital: "Labaid Specialized",
      languages: "Bangla, English",
      bio: "Skin, hair and aesthetic dermatology. Acne, eczema, pigmentation and hair fall.",
      bmdcNumber: "A-50112",
      isOnline: true,
      days: [0, 2, 3, 4, 6],
      hours: ["11:00", "20:00"],
    },
    {
      slug: "dr-imran-chowdhury",
      name: "Dr. Imran Chowdhury",
      specialty: "Pediatrician",
      image: doctorPortrait("photo-1537368910025-700350fe46c7"),
      experience: 14,
      fee: 399,
      rating: 4.7,
      patients: "6.3k+",
      hospital: "Evercare Hospital",
      languages: "Bangla, English",
      bio: "Child health specialist — fever, cough, nutrition and vaccination guidance.",
      bmdcNumber: "A-28744",
      isOnline: false,
      days: [1, 2, 3, 4, 5, 6],
      hours: ["09:00", "17:00"],
    },
    {
      slug: "dr-farhana-akter",
      name: "Dr. Farhana Akter",
      specialty: "Gynecologist",
      image: doctorPortrait("photo-1651008376811-b90baee60c1f"),
      experience: 15,
      fee: 549,
      rating: 4.9,
      patients: "7.0k+",
      hospital: "Ibn Sina Medical",
      languages: "Bangla, English",
      bio: "Women's health — pregnancy care, PCOS, menstrual issues and family planning.",
      bmdcNumber: "A-33401",
      isOnline: true,
      days: [0, 1, 3, 4, 5],
      hours: ["10:00", "19:00"],
    },
    {
      slug: "dr-rafiqul-islam",
      name: "Dr. Rafiqul Islam",
      specialty: "Orthopedic",
      image: doctorPortrait("photo-1622253692010-333f2da6031d"),
      experience: 20,
      fee: 699,
      rating: 4.8,
      patients: "9.4k+",
      hospital: "Apollo Hospitals Dhaka",
      languages: "Bangla, English",
      bio: "Bone & joint specialist — back pain, arthritis, sports injury and fracture follow-up.",
      bmdcNumber: "A-19205",
      isOnline: true,
      days: [1, 2, 3, 4, 5],
      hours: ["09:00", "16:00"],
    },
    {
      slug: "dr-mahbub-alam",
      name: "Dr. Mahbub Alam",
      specialty: "ENT",
      image: doctorPortrait("photo-1582750433449-648ed127bb54"),
      experience: 11,
      fee: 399,
      rating: 4.6,
      patients: "3.1k+",
      hospital: "Popular Diagnostic",
      languages: "Bangla, English",
      bio: "Ear, nose & throat — sinus, tonsillitis, hearing issues and allergy.",
      bmdcNumber: "A-44812",
      isOnline: true,
      days: [0, 1, 2, 4, 5, 6],
      hours: ["10:00", "20:00"],
    },
    {
      slug: "dr-tahmina-begum",
      name: "Dr. Tahmina Begum",
      specialty: "Psychiatrist",
      image: doctorPortrait("photo-1527613426441-4da17471b66d"),
      experience: 13,
      fee: 799,
      rating: 4.9,
      patients: "2.8k+",
      hospital: "National Institute of MH",
      languages: "Bangla, English",
      bio: "Mental health — anxiety, depression, sleep disorders and counselling support.",
      bmdcNumber: "A-37650",
      isOnline: true,
      days: [1, 2, 3, 4, 5, 6],
      hours: ["14:00", "21:00"],
    },
    {
      slug: "dr-anwarul-haque",
      name: "Dr. Anwarul Haque",
      specialty: "Neurologist",
      image: doctorPortrait("photo-1607990281513-2c110a25bd8c"),
      experience: 22,
      fee: 899,
      rating: 4.8,
      patients: "5.5k+",
      hospital: "Bangabandhu Sheikh Mujib",
      languages: "Bangla, English",
      bio: "Neurology consultant — headache, stroke follow-up, neuropathy and seizures.",
      bmdcNumber: "A-15440",
      isOnline: false,
      days: [1, 3, 5],
      hours: ["11:00", "17:00"],
    },
    {
      slug: "dr-salma-khatun",
      name: "Dr. Salma Khatun",
      specialty: "Diabetologist",
      image: doctorPortrait("photo-1591604021695-0c69b7c05981"),
      experience: 16,
      fee: 449,
      rating: 4.7,
      patients: "4.2k+",
      hospital: "BIRDEM General Hospital",
      languages: "Bangla, English",
      bio: "Diabetes & endocrine care — sugar control, lifestyle and medication review.",
      bmdcNumber: "A-29118",
      isOnline: true,
      days: [0, 1, 2, 3, 4, 5, 6],
      hours: ["09:00", "18:00"],
    },
    {
      slug: "dr-tanvir-ahmed",
      name: "Dr. Tanvir Ahmed",
      specialty: "General Physician",
      image: doctorPortrait("photo-1612531386530-97286d97c2d2"),
      experience: 8,
      fee: 199,
      rating: 4.5,
      patients: "2.1k+",
      hospital: "Ahona Care Clinic",
      languages: "Bangla, English",
      bio: "Affordable primary care for common illnesses. Available for instant consults.",
      bmdcNumber: "A-61209",
      isOnline: true,
      days: [0, 1, 2, 3, 4, 5, 6],
      hours: ["08:00", "22:00"],
    },
    {
      slug: "dr-rumana-islam",
      name: "Dr. Rumana Islam",
      specialty: "Dermatologist",
      image: doctorPortrait("photo-1551836022-d5d88e9218df"),
      experience: 9,
      fee: 449,
      rating: 4.8,
      patients: "3.7k+",
      hospital: "Skin Care Bangladesh",
      languages: "Bangla, English",
      bio: "Cosmetic & medical dermatology. Focused on teenage acne and sensitive skin.",
      bmdcNumber: "A-55801",
      isOnline: true,
      days: [1, 2, 3, 4, 5, 6],
      hours: ["12:00", "21:00"],
    },
  ];

  for (const d of doctorSeed) {
    const { days, hours, ...doc } = d;
    const doctor = await prisma.doctor.create({ data: doc });
    await prisma.doctorSchedule.createMany({
      data: days.map((dayOfWeek) => ({
        doctorId: doctor.id,
        dayOfWeek,
        startTime: hours[0],
        endTime: hours[1],
        slotMins: 30,
        isActive: true,
      })),
    });
  }

  // ── Admin users (bcrypt) ───────────────────────────────────────
  const adminHash = await bcrypt.hash("admin123", 10);
  const opsHash = await bcrypt.hash("ops123", 10);
  await prisma.adminUser.create({
    data: {
      email: "admin@ahona.store",
      name: "Ahona Super Admin",
      password: adminHash,
      role: "SUPER_ADMIN",
    },
  });
  await prisma.adminUser.create({
    data: {
      email: "ops@ahona.store",
      name: "Ops Manager",
      password: opsHash,
      role: "OPS",
    },
  });

  // ── Demo coupons ───────────────────────────────────────────────
  await prisma.coupon.createMany({
    data: [
      {
        code: "CHOLBE10",
        description: "10% off store orders",
        type: "PERCENT",
        value: 10,
        minOrder: 500,
        maxDiscount: 200,
        usageLimit: 1000,
        isActive: true,
      },
      {
        code: "WELCOME50",
        description: "৳50 off first orders",
        type: "FIXED",
        value: 50,
        minOrder: 300,
        usageLimit: 500,
        isActive: true,
      },
      {
        code: "FREESHIP",
        description: "Flat ৳60 off delivery (min ৳400)",
        type: "FIXED",
        value: 60,
        minOrder: 400,
        isActive: true,
      },
    ],
  });

  // ── Vendors B2B ────────────────────────────────────────────────
  const vendors = await Promise.all(
    [
      {
        name: "Square Pharmaceuticals Supply",
        slug: "square-pharma-supply",
        phone: "01711000001",
        email: "b2b@square.example",
        city: "Dhaka",
        tradeLicense: "TL-SQ-2024",
        commissionRate: 8,
        status: "ACTIVE" as const,
      },
      {
        name: "Incepta Distribution",
        slug: "incepta-distribution",
        phone: "01711000002",
        email: "vendor@incepta.example",
        city: "Dhaka",
        tradeLicense: "TL-IN-2024",
        commissionRate: 10,
        status: "ACTIVE" as const,
      },
      {
        name: "BeautyHub BD",
        slug: "beautyhub-bd",
        phone: "01711000003",
        city: "Chittagong",
        commissionRate: 12,
        status: "PENDING" as const,
      },
    ].map((v) => prisma.vendor.create({ data: v }))
  );

  // Attach some products to first vendor + sample variants
  const dbProducts = await prisma.product.findMany({
    take: 8,
    orderBy: { createdAt: "asc" },
  });
  if (dbProducts.length && vendors[0]) {
    await prisma.product.updateMany({
      where: { id: { in: dbProducts.slice(0, 5).map((p) => p.id) } },
      data: { vendorId: vendors[0].id, isMedicine: true },
    });
  }
  if (dbProducts[0]) {
    await prisma.productVariant.createMany({
      data: [
        {
          productId: dbProducts[0].id,
          name: "Pack of 10",
          price: dbProducts[0].price,
          stock: 50,
          isDefault: true,
          sku: `VAR-${dbProducts[0].slug}-10`,
        },
        {
          productId: dbProducts[0].id,
          name: "Pack of 30",
          price: Math.round(dbProducts[0].price * 2.7),
          stock: 20,
          isDefault: false,
          sku: `VAR-${dbProducts[0].slug}-30`,
        },
      ],
    });
  }

  // Sample reviews (approved show on storefront; pending needs admin)
  if (dbProducts.length >= 3) {
    await prisma.productReview.createMany({
      data: [
        {
          productId: dbProducts[0].id,
          authorName: "Nusrat A.",
          authorPhone: "01710000011",
          rating: 5,
          title: "Really works",
          body: "Used for two weeks. Skin feels smoother and delivery was fast. Will buy again from Ahona.",
          status: "APPROVED",
          isVerified: true,
          reviewedAt: new Date(),
        },
        {
          productId: dbProducts[0].id,
          authorName: "Karim H.",
          rating: 4,
          title: "Good value",
          body: "Packaging was secure. Product matches the description. Slight delay in courier but quality is fine.",
          status: "APPROVED",
          isVerified: false,
          reviewedAt: new Date(),
        },
        {
          productId: dbProducts[1].id,
          authorName: "Sadia R.",
          authorPhone: "01810000022",
          rating: 5,
          title: "Trusted pharmacy",
          body: "Genuine product and expiry date is far. Happy with Ahona service overall.",
          status: "APPROVED",
          isVerified: true,
          reviewedAt: new Date(),
        },
        {
          productId: dbProducts[1].id,
          authorName: "Pending User",
          rating: 3,
          body: "Okay product but I expected stronger fragrance. Still usable daily.",
          status: "PENDING",
        },
        {
          productId: dbProducts[2].id,
          authorName: "Rafi A.",
          rating: 5,
          title: "Fast delivery",
          body: "Ordered at night, received next day. Highly recommend for regular skincare needs.",
          status: "APPROVED",
          isVerified: true,
          reviewedAt: new Date(),
        },
      ],
    });
    for (const pid of [dbProducts[0].id, dbProducts[1].id, dbProducts[2].id]) {
      const agg = await prisma.productReview.aggregate({
        where: { productId: pid, status: "APPROVED" },
        _avg: { rating: true },
        _count: { _all: true },
      });
      if (agg._count._all > 0 && agg._avg.rating != null) {
        await prisma.product.update({
          where: { id: pid },
          data: {
            rating: Math.round(agg._avg.rating * 10) / 10,
            reviewCount: agg._count._all,
          },
        });
      }
    }
  }

  // ── Riders ─────────────────────────────────────────────────────
  await prisma.rider.createMany({
    data: [
      {
        name: "Karim Mia",
        phone: "01810000001",
        vehicleType: "Bike",
        zone: "Dhanmondi",
        isOnline: true,
        status: "AVAILABLE",
      },
      {
        name: "Rafi Ahmed",
        phone: "01810000002",
        vehicleType: "Bike",
        zone: "Gulshan",
        isOnline: true,
        status: "AVAILABLE",
      },
      {
        name: "Sohel Rana",
        phone: "01810000003",
        vehicleType: "Cycle",
        zone: "Mirpur",
        isOnline: false,
        status: "OFFLINE",
      },
      {
        name: "Nayeem Hasan",
        phone: "01810000004",
        vehicleType: "Van",
        zone: "Uttara",
        isOnline: true,
        status: "BUSY",
      },
    ],
  });

  // ── Lab tests & packages ───────────────────────────────────────
  const labTests = await Promise.all(
    [
      {
        name: "CBC",
        slug: "cbc",
        price: 450,
        comparePrice: 600,
        reportHours: 20,
        bookedCount: 7486,
        category: "Blood",
        image: img.catLab,
        sortOrder: 1,
      },
      {
        name: "Serum Creatinine",
        slug: "serum-creatinine",
        price: 350,
        comparePrice: 450,
        reportHours: 12,
        bookedCount: 4798,
        category: "Kidney",
        image: img.catLab,
        sortOrder: 2,
      },
      {
        name: "Serum Electrolytes",
        slug: "serum-electrolytes",
        price: 500,
        comparePrice: 650,
        reportHours: 12,
        bookedCount: 2943,
        category: "Blood",
        image: img.catLab,
        sortOrder: 3,
      },
      {
        name: "Urine R/E",
        slug: "urine-re",
        price: 250,
        comparePrice: 350,
        reportHours: 12,
        bookedCount: 2624,
        category: "Urine",
        image: img.catLab,
        sortOrder: 4,
      },
      {
        name: "ESR",
        slug: "esr",
        price: 200,
        comparePrice: 300,
        reportHours: 12,
        bookedCount: 2010,
        category: "Blood",
        image: img.catLab,
        sortOrder: 5,
      },
      {
        name: "TSH (Thyroid)",
        slug: "tsh-thyroid",
        price: 600,
        comparePrice: 800,
        reportHours: 12,
        bookedCount: 1975,
        category: "Thyroid",
        image: img.catLab,
        sortOrder: 6,
      },
      {
        name: "HbA1c",
        slug: "hba1c",
        price: 700,
        comparePrice: 900,
        reportHours: 24,
        bookedCount: 3200,
        category: "Diabetes",
        image: img.catLab,
        sortOrder: 7,
      },
      {
        name: "Lipid Profile",
        slug: "lipid-profile",
        price: 800,
        comparePrice: 1100,
        reportHours: 24,
        bookedCount: 2800,
        category: "Heart",
        image: img.catLab,
        sortOrder: 8,
      },
    ].map((t) => prisma.labTest.create({ data: t }))
  );

  const dengueTests = labTests.filter((t) =>
    ["cbc", "esr"].includes(t.slug)
  );
  await prisma.labPackage.create({
    data: {
      name: "Dengue Package",
      slug: "dengue-package",
      price: 1200,
      comparePrice: 1800,
      reportHours: 24,
      description: "CBC + ESR screening package",
      sortOrder: 1,
      items: {
        create: dengueTests.map((t) => ({ testId: t.id })),
      },
    },
  });
  await prisma.labPackage.create({
    data: {
      name: "Full Body Checkup",
      slug: "full-body-checkup",
      price: 3999,
      comparePrice: 6500,
      reportHours: 48,
      description: "Comprehensive health panel",
      sortOrder: 2,
      items: {
        create: labTests.slice(0, 6).map((t) => ({ testId: t.id })),
      },
    },
  });
  await prisma.labPackage.create({
    data: {
      name: "Diabetes Package",
      slug: "diabetes-package",
      price: 1499,
      comparePrice: 2200,
      reportHours: 24,
      sortOrder: 3,
      items: {
        create: labTests
          .filter((t) => ["hba1c", "serum-creatinine"].includes(t.slug))
          .map((t) => ({ testId: t.id })),
      },
    },
  });

  console.log(
    `✓ Seeded — ${categories.length} cats, ${brands.length} brands, ${products.length} products, ${doctorSeed.length} doctors, ${vendors.length} vendors, lab tests, riders, admin`
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
